### ISSUE TITLE
BaseMemcachedCache issue has been fixed?

### ISSUE THREAD

**Issue by gregsadetsky** [memcachier/examples-django#3]
The ["Persistent Connections" README section](https://github.com/memcachier/examples-django#persistent-connections) references a Django issue ([#11331](https://github.com/memcachier/examples-django#persistent-connections)) that seems to have been fixed: [fix](https://github.com/django/django/commit/f02dbbe1ae02c3258fced7b7a75d35d7745cc02a).

Would it make sense to remove the warning paragraph in the README.md? Cheers

**Comment by saschat** [comment]
Thanks for bringing this up!

This example is written with Django 1.8 and for that version this is not fixed yet (it is fixed since 1.11 I think). 

We have more recent examples that use Django 2.1:
-  https://github.com/memcachier/examples-django-tasklist (most comprehensive)
- https://github.com/memcachier/examples-django2

I will highlight the Django version in the README to make sure this is clear.
